﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ModernDirectory.Models;
using Refit;
using System.Globalization;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace ModernDirectory.Services
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedILinkedinService : ILinkedinService
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedILinkedinService(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<Person> GetPeopleAsync(string authorization)
        {
            var arguments = new object[] { authorization };
            return (Task<Person>) methodImpls["GetPeopleAsync"](Client, arguments);
        }

    }
}

namespace ModernDirectory.Services
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedIGooglePlusApi : IGooglePlusApi
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIGooglePlusApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<GooglePeoplePayload> GetPeopleAsync(int pageSize,string nextPageToken)
        {
            var arguments = new object[] { pageSize,nextPageToken };
            return (Task<GooglePeoplePayload>) methodImpls["GetPeopleAsync"](Client, arguments);
        }

        public virtual Task<GooglePeoplePayload> SearchPeopleAsync(string searchQuery,int pageSize,string nextPageToken)
        {
            var arguments = new object[] { searchQuery,pageSize,nextPageToken };
            return (Task<GooglePeoplePayload>) methodImpls["SearchPeopleAsync"](Client, arguments);
        }

    }
}


